name: CI pour Appli Python

on:
    push:
      branches:
        - release

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Set up Python environment
          uses: actions/setup-python@v5
          with:
            python-version: '3.9'
            cache: 'pip'

        - name: Install Python dependencies
          run: pip install -r requirements.txt

        - name: Create Bundle Zip
          run: zip -r code-appli-python_bundle app.py static templates
        
        - name: Upload code-appli-python_bundle.zip
          uses: actions/upload-artifact@v4
          with:
            name: code-appli-python_bundle
            path: . # or path/to/artifact

        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
          with:
            tag_name: ${{ github.run_number }}
            release_name: Release ${{ github.run_number }}
            draft: false
            prerelease: false

        - name: Upload Release Asset
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
          with:
              upload_url: ${{ steps.create_release.outputs.upload_url }}
              asset_path: ./code-appli-python_bundle.zip
              asset_name: code-appli-python_bundle.zip
              asset_content_type: application/zip

        - name: Run flake8 lint
          run: |
            pip install flake8
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics